title: Avi Zaguri
tagline: "Automation Infrastructure Architect | Python Expert"
url: "https://aviz92.github.io"
github:
  username: aviz92
social:
  - https://www.linkedin.com/in/avi-zaguri-41869b11b/
